# Generated by Django 2.2.3 on 2019-10-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventjoined',
            name='day',
        ),
        migrations.RemoveField(
            model_name='eventjoined',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='eventjoined',
            name='time',
        ),
    ]
