# Generated by Django 2.2.3 on 2019-10-22 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(verbose_name='Event Start Date')),
                ('end_date', models.DateTimeField(verbose_name='Event End Date')),
                ('details', models.TextField(verbose_name='Event Details')),
                ('photo', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('rider', models.CharField(max_length=128, verbose_name="Rider's Name")),
                ('horse', models.CharField(max_length=128, verbose_name="Horse's Name")),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Scheduling Notes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Professional'),
        ),
    ]
