# Generated by Django 2.2.3 on 2019-10-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191021_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='short_description',
            field=models.CharField(default='trainer', max_length=256),
            preserve_default=False,
        ),
    ]
