# Generated by Django 2.2.3 on 2019-10-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_professional_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MixPanel',
        ),
        migrations.AlterField(
            model_name='professional',
            name='short_description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventuser',
            unique_together={('event', 'email', 'rider', 'horse')},
        ),
    ]
