# Generated by Django 2.2.3 on 2019-12-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventjoined_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Clinic', 'Clinic'), ('Show', 'Show'), ('Therapy', 'Therapy'), ('Other', 'Other')], default='Other', max_length=200),
            preserve_default=False,
        ),
    ]
