# Generated by Django 2.2.3 on 2019-10-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191022_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventUser',
            new_name='EventJoined',
        ),
        migrations.CreateModel(
            name='AttendeeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('rider', models.CharField(max_length=128, verbose_name="Rider's Name")),
                ('horse', models.CharField(max_length=128, verbose_name="Horse's Name")),
                ('day', models.DateField(verbose_name='Scheduled Day')),
                ('time', models.TimeField(verbose_name='Scheduled Time')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'unique_together': {('event', 'email', 'rider', 'horse')},
            },
        ),
    ]
