# Generated by Django 2.2.3 on 2019-10-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191023_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventjoined',
            name='day',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Scheduled Day'),
        ),
        migrations.AddField(
            model_name='eventjoined',
            name='duration',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='eventjoined',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Scheduled Time'),
        ),
        migrations.DeleteModel(
            name='AttendeeSchedule',
        ),
    ]
