# Generated by Django 2.2.3 on 2020-01-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200125_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule_published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
