# Generated by Django 2.2.3 on 2019-10-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20191023_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, default=None, null=True, verbose_name='Scheduled Day')),
                ('time', models.TimeField(blank=True, default=None, null=True, verbose_name='Scheduled Time')),
                ('duration', models.IntegerField(blank=True, default=None, null=True, verbose_name='Duration')),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.EventJoined')),
            ],
        ),
    ]
