# Generated by Django 2.2.3 on 2019-10-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20191023_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledattendee',
            name='duration',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Duration'),
        ),
    ]
