# Generated by Django 2.2.3 on 2019-10-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventUser',
        ),
        migrations.DeleteModel(
            name='Professional',
        ),
    ]
