# Generated by Django 2.2.3 on 2019-11-09 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20191023_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='thesippelfarm')),
                ('photo_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('caption_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('caption_text', models.TextField(blank=True, default=None, null=True, verbose_name='Event Details')),
                ('order', models.IntegerField()),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='thesippelfarm')),
                ('photo_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('caption_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('caption_text', models.TextField(blank=True, default=None, null=True, verbose_name='Event Details')),
                ('order', models.IntegerField()),
                ('published', models.BooleanField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Page')),
            ],
        ),
    ]
