# Generated by Django 2.2.3 on 2019-11-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191108_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForSaleItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='thesippelfarm')),
                ('content_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('content_text', models.TextField(blank=True, default=None, null=True)),
                ('order', models.IntegerField(blank=True, default=None, null=True)),
                ('published', models.BooleanField()),
            ],
        ),
    ]
